### ISSUE TITLE
[Feature] Systems priorities

### ISSUE THREAD

**Issue by bnoazx005** [bnoazx005/TinyECS#9]
#### Description

A new feature of support of system priorities should be added. Most of ECS frameworks define systems execution order in way all of them added into a system manager (or a queue). But more flexible way is to provide a special option that mark registering system with some priority, e.g from low to high. 

But it's also important to provide backward compatibility with the initial way of systems' registration. So if a user doesn't specify a priority's value a system will be executed in its usual order.

#### TODO list

- [ ] Declare an enumeration which defines all available priorities values

- [ ] Change current definition of methods of ISystemManager to provide a specification of a priority for systems

- [ ] Implement internal representation of a priorities queue

- [ ] Cover the new functionality with tests
